Issue 1331: Change splash page background image
raft-tech/TANF-app pull request #1383
Opened 2021-10-14 21:11 UTC by jorgegonzalez

### Summary of Changes

This PR adds a carousel of new background images to the TDP SplashPage.

Closes issue #1331
_Acceptance criteria as stated in the issue_

### How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Check for the new background images and ensure they change as below.

> *Demo GIF(s) and screenshots for testing procedure*

![2021-10-14 17 08 44](https://user-images.githubusercontent.com/12901172/137396044-09185726-ec3c-4b46-bd63-3bb53fed5333.gif)

### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

+ [x] Look up the acceptance criteria in the related issue; paste ACs below in checklist format.
+ [x] Check against the criteria:
	  - [x] New images are displayed on the front-end landing page.
	  - [ ] Frontend has a timed slideshow of the new images
_we decided that new images would be displayed at the point of refresh instead of addressing a11y issues related to timing_
	  - [x] Testing Checklist has been run and all tests pass
	  - [x] reviewed and tested by @ADPennington and @ttran-hub

As Product Owner, @lfrohlich will decide if ACs are met.

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: ___ (see https://github.com/raft-tech/TANF-app README coverage dashboard)
  + [x] Backend coverage: ___ (see https://github.com/raft-tech/TANF-app README coverage dashboard)

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [ ] Does this PR change any linting or CI settings?

### Deliverable 4: Accessible

> *Performance Standard(s): Web Content Accessibility Guidelines 2.1 AA standards*

> *Acceptable Quality Level: 0 errors reported using an automated scanner and 0 errors reported in manual testing*
+ [x] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
_n/a_
+ [x] Does PR include documentation for Raft's a11y review? 
[here](https://github.com/raft-tech/TANF-app/pull/1383#pullrequestreview-801608648)
+ [x] Did automated and manual testing with @iamjolly and @ttran-hub using Accessibility Insights reveal any errors introduced in this PR?
    + [See the full Accessibility Assessment plan here.](https://github.com/HHS/TANF-app/blob/main/docs/Technical-Documentation/how-government-will-test-a11y.md)
yes [here](https://github.com/raft-tech/TANF-app/pull/1383#issuecomment-970634218)
### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful deployment by assigning a 'Deploy with CircleCI - {env}' label*

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

+ [ ] If this PR introduces backend code, is that code documented both inline and overall?
+ [x] If this PR introduces frontend code, is that code documented both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

+ [x] Does the OWASP Scan pass on CircleCI?
+ [x] Do manual code review and manual testing detect any security issues?
_no new issues detected_

### Deliverable 8: Context

> * Performance Standard(s): Code must be understandable and contextualized for the reviewers possess the knowledge and background necessary for analysis and constructive criticism to take place.

> * Acceptable Quality Level: Code submitted in the pull request has context.*
+ [x] Does this pull request contain sufficient inline comments providing relevant context for code snippets?
+ [x] Is the code understandable and lucid?
+ [x] Does this pull request provide background for why coding decisions were made?
+ [x] Can you as a reviewer explain and take ownership of these elements presented in this code review?

2021-10-14 21:12 UTC, jorgegonzalez commented
I need to add a test or two and then I will open this.

2021-11-01 21:36 UTC, reitermb requested changes
Initial a11y review flagged a lack of user controls compliant to WCAG 2.2.2 (Pause, Stop, Hide) due to a gap in the ticket scope/design documentation. We decided to move back to keying image changes off of page refresh rather than time due to it being a lighter lift than implementing pause controls. The refresh method shouldn’t need to be screened for 2.2.2 as content won’t be animated in and out in real time.

Cc: @lfrohlich @ADPennington @jorgegonzalez

2021-11-09 17:35 UTC, reitermb approved these changes
Approved from a raft a11y/design standpoint! 

WCAG A 2.2.2 (Pause, Stop, Hide) is no longer a concern due to changing content being keyed off of page refresh rather than time. Background images also do not require alt text. 

Recommended/paired to implement a visual styling tweak to add a box-shadow to the login card so as to create better contrast between it and the lighter background images. 

![image](https://user-images.githubusercontent.com/28515874/141012459-ebe6227a-814a-43fb-ac79-43f38ccf688b.png)

2021-11-09 18:28 UTC, jorgegonzalez commented on tdrs-frontend/src/components/SplashPage/SplashPage.jsx
> +        className={`usa-hero usa-hero${randomIndex()}`}
This will toggle through random indexes to iterate through the background pages on every render.

2021-11-12 15:35 UTC, ADPennington commented
@ttran-hub this PR is ready for gov a11y review. cc: @iamjolly 

raft's review is included [here](https://github.com/raft-tech/TANF-app/pull/1383#pullrequestreview-801608648), and you can test this on the [a11y dev site](https://tdp-frontend-a11y.app.cloud.gov/)

2021-11-16 17:14 UTC, ADPennington commented
> @ttran-hub this PR is ready for gov a11y review. cc: @iamjolly
> 
> raft's review is included [here](https://github.com/raft-tech/TANF-app/pull/1383#pullrequestreview-801608648), and you can test this on the [a11y dev site](https://tdp-frontend-a11y.app.cloud.gov/)

@iamjolly, we'd love to get your hot take on this PR. happy to discuss tomorrow when we meet, but please feel free to let us know if you have any a11y  feedback on our workaround strategy for showing a slideshow of pictures on the splash page (i.e. changing photos upon refresh) cc: @ttran-hub

2021-11-16 19:12 UTC, iamjolly commented
@ADPennington - I don't think these changes are live on the [a11y dev site](https://tdp-frontend-a11y.app.cloud.gov/) (at least I think I'm not seeing them)... but I agree that having the images change on refresh make sense and greatly simplify the approach to a11y compared to using images that rotate in/out without a page refresh.

2021-11-16 19:58 UTC, ADPennington commented
> @ADPennington - I don't think these changes are live on the [a11y dev site](https://tdp-frontend-a11y.app.cloud.gov/) (at least I think I'm not seeing them)... but I agree that having the images change on refresh make sense and greatly simplify the approach to a11y compared to using images that rotate in/out without a page refresh.

@iamjolly thanks for the input here! also, we re-deployed to the a11y site, so should be in good shape now 😄

2021-11-16 20:03 UTC, iamjolly commented
@ADPennington and team - I can see the changes and still agree this is good from an a11y perspective - WCAG 2.2.2 is no longer an issue with the image change on page refresh. :)

2021-11-17 18:11 UTC, ADPennington approved these changes
looks good @jorgegonzalez 🚀 cc:@ttran-hub

2021-11-22 14:42 UTC, merged