[Draft] Issue 1521: Updating TANF-app/doc/Background/
raft-tech/TANF-app pull request #1539
Opened 2022-01-12 21:42 UTC by ADPennington

### Summary of Changes
_Provide a brief summary of changes_
Pull request closes #1521 
_Acceptance criteria as stated in the issue_

2022-01-12 21:58 UTC, ADPennington commented on docs/Background/Current-TDRS.md
> +TDRS has a decryption script that runs on transmitted files if (and only if) the files have an "E" as the [encryption indicator in the header record](https://github.com/raft-tech/TANF-app/blob/raft-t
```suggestion
TDRS has a decryption script that runs on transmitted files if (and only if) the files have an "E" as the [encryption indicator in the header record](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/Research/2020%2C%20Fall%20-%20Flat%20File%20Metadata%20Guide.md#header-structure). For future reference: in the absence of checking the header record, if the SSN includes special characters, this is also evidence of encryption.
```

2022-01-12 22:00 UTC, ADPennington commented on docs/Background/Current-TDRS.md
> +TDRS tracks data transmissions from the point that data files are *successfully* picked up for processing (i.e. if files are not picked up, no metadata is tracked) to storage into the dB. Metadata co
```suggestion
TDRS tracks data transmissions from the point that data files are *successfully* picked up for processing (i.e. if files are not picked up, no metadata is tracked) to storage into the dB. Metadata collected include: when the data was processed, the reporting period, all information from the [header record](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/Research/2020%2C%20Fall%20-%20Flat%20File%20Metadata%20Guide.md#header-structure), which tells the system how to process and store the data, and a list of any errors detected by the system. 
```

2022-01-12 22:18 UTC, ADPennington commented on docs/Background/Current-TDRS.md
> +- **[the legacy TDRS](#About-the-TANF-Data-Reporting-Sysyem-(TDRS))**, and
```suggestion
- **[the legacy TDRS](#about-the-tanf-data-reporting-system-tdrs)**, and
```

2022-01-12 22:26 UTC, ADPennington commented on docs/Background/Current-TDRS.md
> +| 2              | Jan 1 – Mar 3   | May 15      |
```suggestion
| 2              | Jan 1 – Mar 31   | May 15      |
```

2022-01-13 14:52 UTC, lfrohlich requested changes
Looks good! Love the new expanded FAQ. Two minor edits noted

2022-01-13 14:52 UTC, lfrohlich commented on docs/Background/README.md
> +* **[Acquisition](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Background/Acquisition/)** - Backgroud on the acquisition process, including the request for quotations (RFQ) and COR d
```suggestion
* **[Acquisition](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Background/Acquisition/)** - Background on the acquisition process, including the request for quotations (RFQ) and COR delegation letters
```

2022-01-13 14:52 UTC, lfrohlich commented on docs/Background/Current-TDRS.md
> +OFA's TANF grantees in the states, territories, and tribes (STTs) are [legislatively-mandated](https://www.law.cornell.edu/uscode/text/42/611) to to report data via TDRS. OFA then aggregates the data
```suggestion
OFA's TANF grantees in the states, territories, and tribes (STTs) are [legislatively-mandated](https://www.law.cornell.edu/uscode/text/42/611) to report data via TDRS. OFA then aggregates the data and uses it for descriptive analyses and program performance monitoring, most notably through the [work participation rate calculations (WPR)](https://www.acf.hhs.gov/ofa/resource-library?f%5B0%5D=program%3A270&f%5B1%5D=program_topic%3A633&f%5B2%5D=type%3Aeasychart&keyword=&sort_by=combined_publication_date). The WPR measures how well states engage families receiving assistance in certain work activities during a fiscal year. STTs must meet both an overall (or “all families”) WPR and a two-parent work participation rate or be subject to a financial penalty.
```

2022-01-13 18:41 UTC, lfrohlich approved these changes

2022-01-13 18:58 UTC, valcollignon approved these changes
Lgtm

2022-01-18 21:41 UTC, merged