Feat/1692 data file upload bug
raft-tech/TANF-app pull request #1699
Opened 2022-03-16 18:30 UTC by riatzukiza

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #_

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Tabletop

- [ ] Ready for Tabletop (Reviewer check this)
- [ ] Tabletop scheduled (Assignee check this)
- [ ] Tabletop approval 

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2022-03-18 16:15 UTC, riatzukiza commented on tdrs-frontend/src/components/Header/Header.test.js
> +        roles: [{ id: 1, name: 'Developer', permissions: [] }],
this is the only role that's suppose to have both permission to data file and permission to admin

2022-03-18 16:16 UTC, riatzukiza commented on tdrs-frontend/src/components/Header/Header.test.js
> +        roles: [{ id: 1, name: 'Developer', permissions: [] }],
open to more tests, though we are still covered over 90% according to code cov

2022-03-22 15:33 UTC, abottoms-coder commented
While the `developer` role can see the data files tab and page, they cannot use it because I don't believe they can be assigned a location within the Django Admin Console. This breaks the AC of #1692

2022-03-22 15:38 UTC, abottoms-coder requested changes
While this addresses frontend changes, the AC of #1692 suggest we need to alter the Django form validation.

2022-03-25 01:53 UTC, reitermb approved these changes
This is good to go from an a11y perspective!

Testing notes:
- There do seem to still be django user/group validation problems (e.g. it wasn't possible for me to test as a developer or a data analyst because it threw an error whenever a location was submitted) 
- Consequently I tested as an OFA Admin. Uploading/submitting now seems to work without a 500 error! 🚀 
- I did get a 400 error on my first attempt but the actual submission turned out to have worked when I refreshed and I was unable to produce the same error on subsequent attempts. 
- You may notice "no file selected" readouts from Voiceover on/around file inputs—this _is_ an a11y issue but is also outside the scope of this issue. #1107 will deliver a fix for that.

2022-03-28 13:34 UTC, abottoms-coder commented
Testing with latest I've found the roles Data Analyst, Developer, OFA Admin and Regional Staff now can see the data files tab and have their stt/region assigned (excluding OFA Admin, rightly). Outside the scope of this ticket, a Regional Staff user can't *use* the data-files tab because they don't have an STT but perhaps this will be resolved in the #1605 epic.

2022-03-28 13:34 UTC, abottoms-coder approved these changes

2022-03-30 16:00 UTC, jorgegonzalez approved these changes

2022-03-30 19:58 UTC, ADPennington commented
@riatzukiza test results below. Please double-check `ofa sys admin` and `ofa regional staff`. i think we need a follow-on ticket to address the ideal behavior for the OFA groups, but for now, what shows in the nav bar isnt aligned with what the permission rules are for these groups:

- `OFA System Admin` cannot see data files tab, but should according to the permission rules  (i wouldn't expect them to be able to actually submit a data file given 1387) ❌ 
![1699p3](https://user-images.githubusercontent.com/63075587/160919082-d29a54b3-a32a-4fb4-b4c7-4e07b6514f60.PNG)

- `OFA Admin` can see data files tab, as expected. and can submit data for any STT ✔️ 
![1699p2](https://user-images.githubusercontent.com/63075587/160918098-623eea22-199d-4f8e-be2f-856d7531138c.PNG)
- `Developer` can see data files tab, as expected. and can submit data for STT in profile ✔️ 
![1699p5](https://user-images.githubusercontent.com/63075587/160918599-facb2dd5-9c7e-4a57-85d3-9e30295abef6.PNG)
- `Data analyst` can see data files tab, as expected. and can submit data for STT in profile ✔️ 
![1699p4](https://user-images.githubusercontent.com/63075587/160918932-59d8ee8d-d00c-467e-afe2-a2ae0ec5a6dd.PNG)

- `OFA Regional Staff` cannot see data files tab, but should according to the permission rules (same note as above re: sys admin). ❌ 
![1699p1](https://user-images.githubusercontent.com/63075587/160918247-77b3287e-44d0-439b-8a07-293599eb4024.PNG)

- `ACF OCIO` cannot see data files tab, as expected. ✔️ 
![1699p6](https://user-images.githubusercontent.com/63075587/160917962-dcb24780-2fce-408b-b74d-79083dd04c4f.PNG)

2022-03-30 19:58 UTC, ADPennington requested changes
see test results. @riatzukiza

2022-04-01 16:23 UTC, ADPennington commented
@riatzukiza thanks for the fix. `ofa regional staff` and ofa system admin` now both see data files tab (below):

![1699p8](https://user-images.githubusercontent.com/63075587/161303653-fc9d7af5-29a4-43d5-94d4-3ad359563996.PNG)
![1699p7](https://user-images.githubusercontent.com/63075587/161303654-9074d6d7-81c1-41b2-9e40-b92703157db4.PNG)

2022-04-01 16:24 UTC, ADPennington approved these changes
🚀 🚀 🚀

2022-04-01 17:07 UTC, merged