Adds submission history dev ready PDFs
raft-tech/TANF-app pull request #1702
Opened 2022-03-18 21:07 UTC by reitermb

## Summary of Changes
Adds dev-ready design PDFs for Submission History V2 / V3 (overlooked adding these after we had the handoff sync for #1290)

V2 supports #1609 
V3 supports #1610, #1612

2022-03-18 21:36 UTC, stevenino commented
@reitermb is there documentation for the current submission portion?

2022-03-21 16:54 UTC, reitermb commented
> @reitermb is there documentation for the current submission portion?

Yeah, that was on the list of past (v0/ATO) release spec we'd discussed not adding to the repo last week, but I did dig up the right Figma pages for it.

The Upload/Download section of https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=3588%3A800 is probably the simplest view of it—with https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4178%3A1794 going into a lot more depth on various edge cases.

2022-03-21 16:58 UTC, stevenino commented
> > @reitermb is there documentation for the current submission portion?
> 
> Yeah, that was on the list of past (v0/ATO) release spec we'd discussed not adding to the repo last week, but I did dig up the right Figma pages for it.
> 
> The Upload/Download section of https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=3588%3A800 is probably the simplest view of it—with https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4178%3A1794 going into a lot more depth on various edge cases.

Ok so all of this has already been implemented in the code?  If so, that works for me. For some reason I just thought there was more for V2. I think once Figma is cleaned up some more (organized in the correct states) things will be more clear.

2022-03-21 19:29 UTC, reitermb commented
> > > @reitermb is there documentation for the current submission portion?
> > 
> > 
> > Yeah, that was on the list of past (v0/ATO) release spec we'd discussed not adding to the repo last week, but I did dig up the right Figma pages for it.
> > The Upload/Download section of https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=3588%3A800 is probably the simplest view of it—with https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4178%3A1794 going into a lot more depth on various edge cases.
> 
> Ok so all of this has already been implemented in the code? If so, that works for me. For some reason I just thought there was more for V2. I think once Figma is cleaned up some more (organized in the correct states) things will be more clear.

Correct! Notifications and onboarding are the two remaining UX lifts for V2—the former will be entirely content driven (and delivered in HTML & hack.md), the former may involve _some_ Figma work, but will also be largely content oriented. So currently the only non-developed Figma spec for V2 is Submission History.

2022-03-21 20:17 UTC, lfrohlich approved these changes
LGTM

2022-03-21 20:17 UTC, ADPennington commented on docs/User-Experience/Dev-Ready-Designs/README.md
> +- [Submission History V2](https://github.com/raft-tech/TANF-app/blob/docs/User-Experience/Dev-Ready-Designs/Submission%20History%20V2.pdf)
could you add a brief blurb on what is represented here.

2022-03-21 20:17 UTC, ADPennington commented on docs/User-Experience/Dev-Ready-Designs/README.md
> +- [Submission History V3](https://github.com/raft-tech/TANF-app/blob/docs/User-Experience/Dev-Ready-Designs/Submission%20History%20V3.pdf)
same suggestion as above @reitermb

2022-03-21 20:18 UTC, ADPennington requested changes
minor suggestions recommended.

2022-03-21 21:53 UTC, stevenino approved these changes

2022-03-29 13:24 UTC, abottoms-coder approved these changes

2022-04-01 13:51 UTC, merged