one line change for a default
raft-tech/TANF-app pull request #1703
Opened 2022-03-21 14:51 UTC by abottoms-coder

## Summary of Changes
_Provide a brief summary of changes_
N/A

2022-03-24 15:26 UTC, abottoms-coder commented
Merged in code from @riatzukiza 's PR for 1692 for testing that files are still scanned. Can spin up with the new alias `tdrs-start-av` or the old alias `tdrs-start` w/o clamav. Neither run owasp/zap.

2022-03-28 18:27 UTC, jorgegonzalez approved these changes

2022-03-28 18:34 UTC, riatzukiza requested changes

2022-03-28 18:34 UTC, riatzukiza commented on tdrs-backend/tdpservice/settings/common.py
> +    CLAMAV_NEEDED = os.getenv('CLAMAV_NEEDED', True)
This wasn't working in the false case. It seems like it is seeing a string of length greater than 0 and accepting that as true. I found this solution:
```suggestion
    CLAMAV_NEEDED = bool(os.getenv('CLAMAV_NEEDED', 'True').lower() in ('true', '1', 't'))
```

Source: https://stackoverflow.com/questions/63116419/evaluate-boolean-environment-variable-in-python

2022-04-01 13:20 UTC, abottoms-coder commented
@riatzukiza Are there still changes you want or is this ready for tabletop?

2022-04-01 13:22 UTC, riatzukiza approved these changes
LGTM

2022-04-05 22:05 UTC, ADPennington approved these changes
👍🏾 apologies the delay. had to troubleshoot spinning up the frontend locally.

2022-04-06 14:44 UTC, merged