Update team-meetings.md
raft-tech/TANF-app pull request #1712
Opened 2022-03-24 20:14 UTC by stevenino

Updating with the new meeting cadence and the updated descriptions of the meetings along with the facilitator role.

## Summary of Changes
Updating with the new meeting cadence and the updated descriptions of the meetings along with the facilitator role.

2022-03-25 14:19 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +- **Format:** Each team member gives an brief and intentional update to answer these questions
```suggestion
- **Format:** Each team member gives a brief and intentional update to answer these questions 
```

2022-03-25 14:22 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +- **Format:** The team will start by reviewing/updating the Sprint Board. We will discuss closed/merged tickets and work in progress tickets to assess thier status for the upcoming sprint. Key metric
```suggestion
- **Format:** The team will start by reviewing/updating the Sprint Board. We will discuss closed/merged tickets and work in progress tickets to assess their status for the upcoming sprint. Key metrics such as velocity will also be analyzed. By the end of the meeting, the team will have a clear understanding of which tickets will continue to be worked in the next sprint and which finished products will be demoed to the team.
```

2022-03-25 14:23 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +- **Format:** Product owner and raft product manager should come prepared with refined priority issues for the team to plan into the sprint. TFor better planning, the team will calculate their capaci
```suggestion
- **Format:** Product owner and raft product manager should come prepared with refined priority issues for the team to plan into the sprint. For better planning, the team will calculate their capacity and point the requested tickets before they pull the work into the sprint. At the end of the meeting the team should have a clear understanding and feel comfortable about completing the new work and rollover work they committed to.
```

2022-03-25 14:24 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +- **Format:** The product owner and raft product manager will collaborate with the leads to review the backlog and prioritize issues in support of the next release and make sure items are ready for t
```suggestion
- **Format:** The product owner and raft product manager will collaborate with the leads to review the backlog and prioritize issues in support of the next release and make sure items are ready for the upcoming Sprint Planning session. By the end of the session, there will be a common understanding of the upcoming priorities and acceptance criteria of refined issues. The refined set of issues should be sent to the sprint board before Sprint Planning. If there are outstanding questions on a particular issue they will be noted within the unrefined issue and remain in the backlog. The agenda and notes can be found in the [Product Notebook](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Product.one%7Ccfbcc7fb-4b00-4c43-9e29-70bdedd83b98%2FBacklog%20Refinement%7C4ef1b64b-327d-4628-823a-0d1fc5fce6ea%2F%29) within the TDP OneNote.
```

2022-03-25 14:26 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +- **When:** Every other Tuesday 1:15pm-1:45pm
```suggestion
- **When:** Every other Tuesday 2:00pm-2:30pm EST, as needed
```

2022-03-25 14:27 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +- **Format:** This meeting is a formal version of internal demo with an emphasis on demonstrating work to stakeholders outside the product team. This demo should emphasize completed work that has a d
```suggestion
- **Format:** This meeting is a formal version of internal demo with an emphasis on demonstrating work to stakeholders outside the product team. This demo should emphasize completed work that has a direct impact to the end user, it should not be a status of the work that has been done. The author of the feature will demo new work and features to the attendees. How attendees give feedback on the demo needs to be determined. 
```

2022-03-25 14:29 UTC, lfrohlich commented on docs/How-We-Work/team-meetings.md
> +* **Format:** The agenda can be found in the [Product Notebook](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit
```suggestion
* **Format:** The agenda can be found in the [Product Notebook](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Product.one%7Ccfbcc7fb-4b00-4c43-9e29-70bdedd83b98%2FCross%20Product%20Sync%7Cec320778-42b6-43dc-af81-72494962f7bb%2F%29) within the TDP OneNote. Notes and action items are kept here as well. All attendees are invited to add to the agenda prior to the meeting. Raft and OFA Product Team use this time as a biweekly discussion and debrief. Participants discuss the status and updates to the roadmap, releases, high priority items.
```

2022-03-25 14:30 UTC, lfrohlich approved these changes
Fixed some typos and made some clarifications throughout.

2022-03-28 19:12 UTC, ADPennington commented on docs/How-We-Work/team-meetings.md
> +- **Format:** The team will start by demoing completed work that was identified during sprint review. By the end of the meeting, we will have an apprecition of the work that was completed in the last
```suggestion
- **Format:** The team will start by demoing completed work that was identified during sprint review. By the end of the meeting, we will have an appreciation of the work that was completed in the last two weeks. The team should decide what is ready to be demoed (and label it as “demo”), who will conduct the demo/s, and if special guests should be invited to attend the larger demo event later in the day. All demoed issues must be merged first. Facilitator will take note of what issues will be demoed and who will be presenting for each issue. OFA Product Owner and OFA Tech Lead will sign off on Raft's recommendation of issues to be demoed.
```

2022-03-28 19:14 UTC, ADPennington requested changes
looks great @stevenino. just a few suggestions from @lfrohlich and me.

2022-03-28 20:01 UTC, stevenino commented
> looks great @stevenino. just a few suggestions from @lfrohlich and me.

Thanks @ADPennington. I accepted all of the suggestions.

2022-03-28 20:40 UTC, ADPennington reviewed
👍🏾

2022-03-29 13:28 UTC, abottoms-coder approved these changes

2022-03-29 13:41 UTC, merged