Feat/1680 profile stt unapproved
raft-tech/TANF-app pull request #1900
Opened 2022-06-22 18:46 UTC by riatzukiza

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #1680 

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```
Create a new user and fill out the request access form, by default you should see the stt you sent in the request.
If the user has a region associated with them, the region is used instead. The backend is already enforcing this.
if there neither was submitted, then neither is set, and it will say federal government

## Tabletop

- [ ] Ready for Tabletop (Reviewer check this)
- [ ] Tabletop scheduled (Assignee check this)
- [ ] Tabletop approval 

## Deliverables
_More details on how deliverables herein are assessed included [here](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] Unapproved grantee user has requested STT in profile upon submitting request form
- [x] Unapproved ACF user has "Federal Government" in profile upon submitting request form
- [x] Unapproved grantee user profile also displays inferred region upon submitting request form
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [x] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [x] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2022-06-27 15:10 UTC, andrew-jameson requested changes
Deployed, not seeing Region per AC? Glad to see selected STT is correct and present though

![image](https://user-images.githubusercontent.com/84722778/175973490-7c83e162-c974-4ebd-84ed-88538084ca2e.png)

2022-06-27 20:07 UTC, reitermb approved these changes
All looks good from an a11y standpoint! (e.g. no adverse impact to existing page nav/reading behavior)

2022-06-28 14:45 UTC, riatzukiza commented
> Deployed, not seeing Region per AC? Glad to see selected STT is correct and present though
> 
> ![image](https://user-images.githubusercontent.com/84722778/175973490-7c83e162-c974-4ebd-84ed-88538084ca2e.png)

I have fixed this:
![image](https://user-images.githubusercontent.com/10676925/176208904-936e9d58-80e3-4514-93f2-e9565b3ce712.png)

2022-06-29 14:00 UTC, andrew-jameson commented
As a federal government user, I get a blank "Region" line below the rest of my profile. Is this a quick fix? @riatzukiza

2022-06-29 14:02 UTC, andrew-jameson commented on tdrs-frontend/src/components/Profile/Profile.jsx
> +          console.log(user)
Do we want to retain these lines? Were they just for debugging?

2022-06-29 17:03 UTC, riatzukiza commented on tdrs-frontend/src/components/Profile/Profile.jsx
> +          console.log(user)
```suggestion
```

2022-07-06 18:55 UTC, n0remac commented on tdrs-frontend/src/components/Profile/Profile.jsx
> +        {(() => {
Might be cleaner and easier to visually parse to have this arrow function as its own function. I'd defer to someone else on that though.

2022-07-06 21:36 UTC, n0remac commented
I don't think it was part of this ticket, but it might be worth it to change out the button link to something like:
```
           <a
              href="https://idp.int.identitysandbox.gov/account"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button
                className="usa-button"
                type="button"
                id="loginDotGovSignIn"
              >
                <div className="mobile:margin-x-auto mobile-lg:margin-0">
                  Manage Your Account at{' '}
                  <img
                    className="mobile:margin-x-auto mobile:padding-top-1 mobile-lg:margin-0 mobile-lg:padding-top-0 width-15 padding-left-1"
                    src={loginLogo}
                    alt="Login.gov"
                  />
                </div>
                <span className="visually-hidden">Opens in a new website</span>
              </Button>
            </a>
```

I noticed a couple of these onclick buttons in the code. IDK if there is a reason for them or not. I am pretty sure the hrefs are more secure and offer other features. The top answer on this SO thread explains it well https://stackoverflow.com/questions/1667416/window-location-href-vs-clicking-on-an-anchor

2022-07-08 13:45 UTC, andrew-jameson approved these changes
LGTM but would be interested to hear discussion around @n0remac 's suggestion on the links.

2022-07-12 19:25 UTC, n0remac approved these changes

2022-07-13 14:32 UTC, ADPennington approved these changes
non-acf user upon submitting request
![1900p1](https://user-images.githubusercontent.com/63075587/178758750-9089b741-fe90-45ba-b1a9-8be79022bae5.PNG)

non-acf user after permissions set
![1900p4](https://user-images.githubusercontent.com/63075587/178758857-3bf01cae-de30-4e53-a5e7-0392ae4a2ebc.PNG)

acf user upon request
![1900p3](https://user-images.githubusercontent.com/63075587/178758972-2b5587c0-151f-4f7e-940c-b8bcfe424206.PNG)

acf user after permission set
![1900p5](https://user-images.githubusercontent.com/63075587/178759384-ee08dc70-1e55-4edf-94aa-34afb4db0d8a.PNG)

2022-07-18 13:35 UTC, merged