Feat/1787 site map
raft-tech/TANF-app pull request #1944
Opened 2022-07-11 19:40 UTC by riatzukiza

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #_

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2022-07-11 19:53 UTC, riatzukiza commented
I need to write tests for this, otherwise it is ready for code/a11y reviews.

2022-07-11 20:04 UTC, n0remac commented on tdrs-frontend/src/components/Footer/Footer.jsx
> +                    rel="noreferrer"
add noopener

2022-07-11 20:08 UTC, riatzukiza commented on tdrs-frontend/src/components/SiteMap/SiteMap.jsx
> +      text="Home"
```suggestion
      text="Admin"
```

2022-07-12 16:25 UTC, n0remac commented on tdrs-frontend/src/components/Footer/Footer.jsx
> +                      rel="noreferrer"
add noopener

2022-07-12 16:28 UTC, n0remac commented on tdrs-frontend/src/components/Footer/Footer.jsx
> +                  <li className="mobile-lg:grid-col-6 desktop:grid-col-auto usa-footer__primary-content">
I never used mobile-lg. We should probably look through the frontend together at some point to get our styling as consistent as possible. Maybe we can save something like that for when we don't have such a big deadline.

2022-07-12 16:41 UTC, n0remac commented on tdrs-frontend/src/components/SiteMap/SiteMap.jsx
> +    <SiteMap.Link text="Home" link="/home" />
Can you explain what is going on here? You are referencing the SiteMap variable as it's building itself?

2022-07-12 16:46 UTC, n0remac commented on tdrs-frontend/src/components/SiteMap/SiteMap.jsx
> +const SiteMap = () => (
Maybe, just add a note here to remind people to update the tests when a new link is added

2022-07-12 16:47 UTC, n0remac requested changes
Only a couple little changes. All the code looks really good.

2022-07-14 18:16 UTC, n0remac commented on tdrs-frontend/src/components/Footer/Footer.jsx
> +                  <li className="mobile-lg:grid-col-6 desktop:grid-col-auto usa-footer__primary-content">
I changed the footer in my pr too 
https://github.com/raft-tech/TANF-app/pull/1924/files#diff-9fabec8f76eaeefca82056f5b7fb1288c54eaaa656dcfcb54473eb4413102796

2022-08-03 20:39 UTC, n0remac commented on tdrs-frontend/src/components/SiteMap/SiteMap.test.js
> +  it('When an authenticated Developer visits the sitemap', () => {
Developer should see admin

2022-08-03 20:42 UTC, n0remac commented on tdrs-frontend/src/components/SiteMap/SiteMap.test.js
> +  it('When an authenticated Developer visits the sitemap', () => {
test all roles

2022-08-10 20:51 UTC, n0remac approved these changes

2022-08-11 16:53 UTC, closed without merging