updating csv file columns after talking with ux
raft-tech/TANF-app pull request #2472
Opened 2023-04-03 19:24 UTC by andrew-jameson

## Summary of Changes
After discussion with UX, I've put in a filter to only render specific columns in a specific order to make this more user-friendly.

2023-04-03 20:00 UTC, Smithh-Co approved these changes
Ty for the quick action Andrew! LGTM

2023-04-03 20:02 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/models.py
@raftmsohani It seems to me we overlooked this previously. This should have been flipped, yes?

2023-04-03 20:11 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/views.py
> +                          'column_number']
@reitermb @lilybl1 Are these columns more inline with your vision?

2023-04-04 14:01 UTC, raftmsohani approved these changes
LGTM!

2023-04-04 14:56 UTC, reitermb approved these changes
Changes look great to me—thanks for the super quick turnaround too!

2023-04-05 13:30 UTC, raftmsohani commented on tdrs-backend/tdpservice/parsers/migrations/0002_auto_20230403_1934.py
> +            field=models.TextField(max_length=128, null=True),
rpt_month_year should be 'int', see https://github.com/raft-tech/TANF-app/blob/223e5f115fa304cfd534790adae18a65c10793ec/tdrs-backend/tdpservice/search_indexes/models.py#L19

2023-04-05 13:41 UTC, raftmsohani requested changes
I made a new comment for 'rpt_month_year'

2023-04-07 14:48 UTC, raftmsohani approved these changes
Looks good to me :)

2023-04-26 21:22 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/models.py
> +    case_number = models.IntegerField(null=True, blank=False)
@andrew-jameson @reitermb @lilybl1 case number can have alphanumeric characters.

2023-04-27 17:59 UTC, ADPennington approved these changes
👍🏾

2023-04-27 19:31 UTC, merged