Adding "beta" banners to relevant error report sections
raft-tech/TANF-app pull request #2522
Opened 2023-05-11 16:36 UTC by andrew-jameson

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #_

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2023-05-11 17:15 UTC, Smithh-Co approved these changes

2023-05-22 15:35 UTC, reitermb commented on tdrs-backend/tdpservice/parsers/views.py
> +        worksheet.write(row, col, "BETA TESTING - PLEASE DO NOT USE - REFER TO LEGACY TDRS EMAILS")
```suggestion
        worksheet.write(row, col, "Error reporting in TDP is still in development. We'll be in touch when it's ready to use! For now please refer to the reports you receive via email")
```

2023-05-22 15:37 UTC, reitermb commented on tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.jsx
> +                <th>**IN BETA** Error Reports</th>
```suggestion
                <th>Error Reports (In development)</th>
```

2023-05-22 15:39 UTC, reitermb commented on tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.test.js
> +    expect(screen.queryByText('**IN BETA** Error Reports')).toBeInTheDocument()
```suggestion
    expect(screen.queryByText('Error Reports (In development)')).toBeInTheDocument()
```

2023-05-22 15:40 UTC, reitermb requested changes
All requested changes added as inline suggestions

2023-05-22 15:48 UTC, reitermb commented on tdrs-backend/tdpservice/parsers/views.py
> +        worksheet.write(row, col, "BETA TESTING - PLEASE DO NOT USE - REFER TO LEGACY TDRS EMAILS")
In addition to the above copy tweak could we add a blank row between this message and the column headers for some added visual separation

2023-05-22 17:43 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/views.py
> +        row, col = 1, 1
```suggestion
        row, col = 2, 0
```

2023-05-22 17:56 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/views.py
> +        worksheet.write(row, col, "Error reporting in TDP is still in development. We'll be in touch when it's ready to use! For now please refer to the reports you receive via email")
```suggestion
        worksheet.write(row, col, \
                                   "Error reporting in TDP is still in development. We'll be in touch when it's ready to use! \
                                    For now please refer to the reports you receive via email")
```

2023-05-22 17:59 UTC, reitermb approved these changes
Looks good! 🙌

2023-05-22 18:04 UTC, ADPennington commented
@andrew-jameson circleci tests need a little help

2023-05-22 19:31 UTC, andrew-jameson commented
> @andrew-jameson circleci tests need a little help

Yup, should be addressed now. The new text was too longer for linting.

2023-06-02 16:56 UTC, ADPennington approved these changes

2023-06-02 17:43 UTC, merged