Item Number Mismatch
raft-tech/TANF-app pull request #2578
Opened 2023-06-15 21:49 UTC by elipe17

## Summary of Changes
- Updated RowSchema and Models to reference correct item number
- Converted item number to string to capture subcategories in certain items
- Added missing field to M1 schema
Pull request closes #2564 

## How to Test
```
cd tdrs-frontend && docker-compose up
cd tdrs-backend && docker-compose up
```
- Authenticate as a user who can submit both tanf and ssp datafiles
- Submit a valid and invalid file. Verify the valid files records were created and that the appropriate ParserError objects were created for the invalid file(s). In the ParserError object, verify that the item number is correct wrt (the references here)[https://www.acf.hhs.gov/ofa/policy-guidance/final-tanf-ssp-moe-data-reporting-system-transmission-files-layouts-and-edits]

## Deliverables
_More details on how deliverables herein are assessed included [here](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] Item numbers are correctly referenced

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2023-06-20 13:15 UTC, jtimpe approved these changes

2023-06-20 13:36 UTC, raftmsohani approved these changes
LGTM! Just be careful with migration, maybe run it on a clone of production to see the impact first

2023-06-20 18:54 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
> +        Field(item="47C", name='WORK_EXPERIENCE_HOL', type='number', startIndex=74, endIndex=76,
```suggestion
        Field(item="46C", name='WORK_EXPERIENCE_HOL', type='number', startIndex=74, endIndex=76,
```

2023-06-20 18:56 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
> +        Field(item="48", name='OJT', type='number', startIndex=76, endIndex=78,
@elipe17 this is 47, and so on thereafter this. [reference](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BD750ECCD-B320-4E7A-B7F6-C9354B84F61B%7D&file=TDP_Validation_SSP_Section1.xlsx&action=default&mobileredirect=true)

2023-06-20 21:30 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
> +        Field(item="26BI", name='RECOUPMENT_PRIOR_OVRPMT', type='number', startIndex=102, endIndex=106,
```suggestion
        Field(item="26B", name='RECOUPMENT_PRIOR_OVRPMT', type='number', startIndex=102, endIndex=106,
```

2023-06-20 21:31 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
> +        Field(item="26BII", name='OTHER_TOTAL_REDUCTIONS', type='number', startIndex=106, endIndex=110,
@elipe17 this should be 26ci. everything after this needs an update. see [here](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BF99CEA75-18CC-4494-9302-677CC92E3EF4%7D&file=TDP_Validation_TANF_Section1.xlsx&action=default&mobileredirect=true)

2023-06-20 21:35 UTC, ADPennington requested changes
@elipe17 looks good; just a couple of the schemas need updated item numbers. 

Also can you confirm, should I see item numbers in the schemas in DAC?

2023-06-21 17:58 UTC, andrew-jameson reviewed
Besides the ordering issues Alex brought up, this looks straight-forward. Will test once those updates are live.

2023-06-22 15:02 UTC, elipe17 commented
> @elipe17 looks good; just a couple of the schemas need updated item numbers.
> 
> Also can you confirm, should I see item numbers in the schemas in DAC?

Updated the item numbers. And I apologize, you will not see the item numbers in DAC.

2023-06-22 19:55 UTC, ADPennington approved these changes
🚀

2023-06-23 20:24 UTC, merged