Spot check remediations
raft-tech/TANF-app pull request #262
Opened 2020-09-11 19:36 UTC by hilvitzs

### This pull request changes...

- expected change 1
- expected change 2

### [AC] This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] Vulnerability Scan Test (Zap) has no high/critcial CVEs
- [ ] Linting Tests (ESLint for UI and Flake8 for Python)
- [ ] Unit Tests ( including a code coverage test report)
- [ ] Accessibility Tests (Pa11y UI Only)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### [DoD] This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2020-09-15 16:25 UTC, hilvitzs commented
After discussions with @carltonsmith, @shubhi-raft, and @lauraGgit we are going to remove trussworks from our project. It is just not quite mature enough to be used currently. Here is the issue: https://github.com/raft-tech/TANF-app/issues/274.

2020-09-15 19:23 UTC, RafterGit requested changes

2020-09-15 19:23 UTC, RafterGit commented on tdrs-frontend/src/theme/_global.scss
> +// $theme-font-path: '~uswds/src/fonts';
@hilvitzs  Does this commented out code serve a purpose or can it be deleted?

2020-09-15 21:12 UTC, RafterGit approved these changes

2020-09-16 14:48 UTC, lauraGgit reviewed
The deployed version currently has the logo in the footer, but the local version from this branch does not. Can you add in that code here and it will be good to go?

2020-09-16 14:58 UTC, hilvitzs commented
I'm not sure how the deployed was different than the branch but I just pushed with the ACF logo replacing the placeholder.

2020-09-16 15:44 UTC, lauraGgit approved these changes

2020-09-16 20:07 UTC, merged