Tribal Section 2 Parsing & Validation
raft-tech/TANF-app pull request #2753
Opened 2023-11-21 21:51 UTC by elipe17

## Summary of Changes
- Added support for Tribal TANF section 1 parsing and validation
Pull request closes #1115 

## How to Test
```
cd tdrs-frontend && docker-compose up
cd tdrs-backend && docker-compose up
```

1. Open http://localhost:3000/ and sign in.
- Submit both `ADS.E2J.FTP2.TS142.txt` 
- Verify the file generates Tribal T4/T5 records.

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [ ] Allow Tribes to submit Closed Data based on the TANF data parsing spec

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2023-11-30 15:21 UTC, andrew-jameson approved these changes
LGTM

2023-12-01 13:01 UTC, raftmsohani commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
> +                    item="0",
Please add friendly_name for each field as per #2599

2023-12-01 13:02 UTC, raftmsohani submitted a review, later dismissed
Please add friendly_name for each field. for ref, look at 2599

2023-12-01 15:38 UTC, jtimpe approved these changes
Agree with Mo about adding a `friendly_name`, otherwise looks good!

2023-12-13 15:27 UTC, George-Hudson approved these changes
LGTM

2023-12-20 19:16 UTC, elipe17 commented
@ADPennington, Updated based on your feedback and got it deployed to QASP.

2024-01-04 20:20 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
> +                    required=True,
```suggestion
                    required=False,
```

2024-01-04 20:34 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
> +                    required=True,
```suggestion
                    required=False,
```

2024-01-04 20:36 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
> +                    validators=[validators.isInLimits(1, 2)],
```suggestion
                    validators=[validators.isInLimits(0, 2)],
```

2024-01-04 20:41 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
> +                    required=True,
```suggestion
                    required=False,
```

2024-01-04 20:41 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
> +                    validators=[validators.isInLimits(1, 2)],
```suggestion
                    validators=[validators.isInLimits(0, 2)],
```

2024-01-04 21:04 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
> +                validators.if_then_validator(
@elipe17 this can be dropped. we cant validate this without calculating age.

2024-01-04 21:10 UTC, ADPennington approved these changes
@elipe17 this is in good shape. a few suggestions/comments on validators included below. once these are addressed, please re-deploy :)

2024-01-04 21:12 UTC, ADPennington requested changes
changes requested.

2024-01-04 23:10 UTC, elipe17 commented
@ADPennington deploying now

2024-01-05 14:10 UTC, ADPennington approved these changes
🚀

2024-01-08 16:29 UTC, merged

2024-01-08 16:57 UTC, raftmsohani commented on tdrs-backend/tdpservice/search_indexes/test/test_model_mapping.py
> +    assert response.hits.total.value == 1
can we assert specific fields instead?

2024-01-08 17:16 UTC, raftmsohani commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
> +from ...util import SchemaManager
Note: I have moved the SchemaManager in my PR, depending on who merges first we might see a conflict

2024-01-08 17:39 UTC, raftmsohani approved these changes
LGTM!