Tribal Section 3 Parsing & Validation
raft-tech/TANF-app pull request #2761
Opened 2023-11-29 18:38 UTC by elipe17

## Summary of Changes
- Added support for parsing and validating Tribal TANF T6 records
Pull request closes #1116 

## How to Test
```
cd tdrs-frontend && docker-compose up
cd tdrs-backend && docker-compose up
```

1. Open http://localhost:3000/ and sign in.
- Submit both `ADS.E2J.FTP3.TS142` 
- Verify the file generates 3 Tribal T6 records.

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [ ] Allow Tribes to submit Closed Data based on the TANF data parsing spec
- [ ] README is updated, if necessary

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2023-12-01 13:03 UTC, raftmsohani requested changes
Please add friendly_name to t6 fields

2023-12-15 16:22 UTC, jtimpe approved these changes

2023-12-18 18:20 UTC, raftmsohani approved these changes
LGTM!

2024-01-05 17:31 UTC, elipe17 commented
@ADPennington this is up to date and is ready. Deploying for you now.

2024-01-05 19:11 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of approved cases",
```suggestion
            friendly_name="total number of approved applications",
```

2024-01-05 19:14 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of denied",
```suggestion
            friendly_name="total number of denied applications",
```

2024-01-05 19:16 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of two parents families",
```suggestion
            friendly_name="total number of two parent families",
```

2024-01-05 19:17 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of no-parent family",
```suggestion
            friendly_name="total number of no parent family",
```

2024-01-05 19:17 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of one parent families",
```suggestion
            friendly_name="total number of one-parent families",
```

2024-01-05 19:18 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total of number of families",
```suggestion
            friendly_name="total number of families",
```

2024-01-05 19:19 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="number of families",
```suggestion
            friendly_name="total number of families",
```

2024-01-05 19:25 UTC, ADPennington requested changes
looks good @elipe17. a few suggestions on inconsistencies in the friendly names. I imagine these are also incorrect in [TANF T6 schema](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py) as well, so a follow-up ticket forthcoming.

2024-01-05 20:33 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of no parent family",
```suggestion
            friendly_name="total number of no parent families",
```

2024-01-05 20:37 UTC, ADPennington commented on tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
> +            friendly_name="total number of two parent families",
```suggestion
            friendly_name="total number of two-parent families",
```

2024-01-05 20:38 UTC, ADPennington reviewed
caught a couple more @elipe17. I can approve upon commit.

2024-01-05 20:54 UTC, elipe17 commented
> caught a couple more @elipe17. I can approve upon commit.

Updated!

2024-01-05 21:30 UTC, ADPennington approved these changes
🚀

2024-01-08 16:30 UTC, andrew-jameson commented
@elipe17 Can you resolve merge conflicts here?

2024-01-08 16:51 UTC, elipe17 commented
> @elipe17 Can you resolve merge conflicts here?

@andrew-jameson resolved :)

2024-01-08 16:52 UTC, merged