Feat/2813 reduce dev env
raft-tech/TANF-app pull request #2827
Opened 2024-02-01 14:53 UTC by andrew-jameson

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #2813 

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-02-01 20:27 UTC, elipe17 approved these changes
Looks good to me! I didn't see any sandbox items alive in cloud.gov and didn't find any other references to it in the repo.

2024-02-07 21:52 UTC, jtimpe approved these changes

2024-02-13 14:16 UTC, ADPennington commented on docs/Technical-Documentation/diagrams/tdp-environments.drawio
@andrew-jameson did [the PNG version](https://github.com/raft-tech/TANF-app/blob/feat/2813-reduce-dev-env/docs/Technical-Documentation/diagrams/tdp-environments.png) of this diagram get updated too?

2024-02-13 14:21 UTC, ADPennington reviewed
@andrew-jameson couple of questions on this:

- does the PNG version of system arch diagram also need to be updated?
- I checked the dev environment for apps and services related to sandbox and noticed these services. do these need to be deleted?


```
tdp-storage-sandbox
tdp-redis-sandbox
```

2024-02-16 13:43 UTC, ADPennington requested changes
re: system diagram update. Please also confirm if the additional services I found need to be deleted.

2024-02-16 15:16 UTC, andrew-jameson commented
> @andrew-jameson couple of questions on this:
> 
>     * does the PNG version of system arch diagram also need to be updated?
> 
>     * I checked the dev environment for apps and services related to sandbox and noticed these services. do these need to be deleted?
> 
> 
> ```
> tdp-storage-sandbox
> tdp-redis-sandbox
> ```

Updated png file, deleted redis service. There's an issue with the storage service that I'm working through:

```
"errorResponse": {
    "description": "Service instance tdp-storage-sandbox: Service broker error: BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
    ....
    {
  "error": {
    "statusCode": 403,
    "status": "403 Forbidden"
  },
  "errorResponse": {
    "description": "You are not authorized to perform the requested action",
    "error_code": "CF-NotAuthorized",
    "code": 10003
  }
}
```

I'll let you know when I've cleared this service out but it won't impact other functionality.

2024-02-18 00:37 UTC, ADPennington approved these changes
lgtm @andrew-jameson 👍🏾 please check with cloud.gov if we're still blocked from removing sandbox services in dev when this merges. 

test notes [here](https://hackmd.io/P4sQkTRORLGjiodfgRwMtA?view#Feat2813-reduce-dev-env)

2024-02-20 14:28 UTC, merged