Case Number Validators
raft-tech/TANF-app pull request #2834
Opened 2024-02-07 15:21 UTC by elipe17

## Summary of Changes
- Updated CASE_NUMBER validators to `notEmpty` to allow any characters but error on all spaces.
Pull request closes #2794 

## How to Test

```
cd tdrs-frontend && docker-compose up
cd tdrs-backend && docker-compose up
```

1. Open http://localhost:3000/ and sign in.
2. submit a datafile with a record that has a case number of all spaces and a record that has some spaces and maybe other characters.
3. verify only one CASE_NUMBER parser error was generated for the all spaces case

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
 - [ ] `CASE_NUMBER` validator is updated to capture all possible variations and error messages aren't raised 
 - [ ] Testing Checklist has been run and all tests pass
 - [ ]  README is updated, if necessary

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-02-08 13:59 UTC, jtimpe approved these changes

2024-02-09 14:31 UTC, andrew-jameson approved these changes

2024-02-12 15:08 UTC, raftmsohani approved these changes
LGTM!

2024-02-13 17:50 UTC, ADPennington requested changes
@elipe17  I noticed a couple of things during testing:

- it appears that when the case number is space-filled, the record is still parsed, but the feedback suggests the record is not able to be parsed.  I dont think the record should be parsed since we cannot do anything with the record if it is missing the case number. 
- Related to the above, the count of records unable to be parsed when the case number is space-filled seems inaccurate. 

my qasp notes are here: https://hackmd.io/P4sQkTRORLGjiodfgRwMtA?view#Case-Number-Validators

2024-02-15 21:16 UTC, ADPennington approved these changes
lgtm 👍🏾 

- pre-parsing check for blank case numbers added ✔️ 
- duplicated count of records not parse-able resolved ✔️ 
- i added a note for @reitermb desired output on the pre-parsing language to #2673 
- i added a note for `dev` on #2754 re: data processing status for incomplete sections 1 and 2 files.

2024-02-16 14:43 UTC, merged