Move over changes from Camilla's branch
raft-tech/TANF-app pull request #2868
Opened 2024-02-28 20:39 UTC by reitermb

## Summary of Changes
Fresh PR for Camilla's work fixing a number of broken links in the research syntheses folder

2024-03-08 18:59 UTC, lfrohlich requested changes
Made a few comments, otherwise looks good

2024-03-08 18:59 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Fall - Flatfile Metadata Guide.md
> +🔍 **Research**: There are open questions and we’d like to base a recommendation on insights from Phase III Research ([October STT Research](https://github.com/HHS/TANF-app/blob/main/docs/User-Experie
```suggestion
🔍 **Research**: There are open questions and we’d like to base a recommendation on insights from Phase III Research ([October STT Research](https://github.com/HHS/TANF-app/blob/main/docs/User-Experience/Research-Syntheses/2020%2C%20Fall%20-%20Understanding%20STT%20Roles%2C%20Source%20of%20Truth%2C%20and%20Metadata.md)) and continued solutions ideation (Both design and technical).
```

2024-03-08 18:59 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2021, Spring - Evil User Journeys & TANF Data Errors.md
> +- The [evil user journey maps](https://github.com/HHS/TANF-app/blob/main/docs/User-Experience/Research-Syntheses/2021%2C%20Spring%20-%20Evil%20User%20Journeys%20%26%20TANF%20Data%20Errors.md) :lock:
```suggestion
- The [evil user journey maps](https://github.com/HHS/TANF-app/blob/main/docs/User-Experience/Research-Syntheses/2021%2C%20Spring%20-%20Evil%20User%20Journeys%20%26%20TANF%20Data%20Errors.md) synthesized from both workshops can be used to generate acceptance criteria for continued work on TDP. 
```

2024-03-08 18:59 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2022, Fall - TDP 2.2 Pilot Expansion.md
> +In addition to reviewing new functionality, we wanted to revisit and retest the areas noted from the August 2022 pilot program. Please reference [August 2022](https://github.com/HHS/TANF-app/blob/mai
```suggestion
In addition to reviewing new functionality, we wanted to revisit and retest the areas noted from the August 2022 pilot program. Please reference [August 2022](https://github.com/HHS/TANF-app/blob/main/docs/User-Experience/Research-Syntheses/2022%2C%20Summer%20-%20TDP%202.0%20Pilot%20Program.md) for full details 
```
I think we want to link to August 2022 instead but please double check

2024-03-08 18:59 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2023, Winter - TDP 3.0 Pilot Program.md
> +Following the [January 2023 research session](https://github.com/HHS/TANF-app/blob/main/docs/User-Experience/Research-Syntheses/2023%2C%20Winter%20-%20TDP%203.0%20Pilot%20Program.md) on error message
Is this right? It's self referential. Should it be https://github.com/HHS/TANF-app/blob/main/docs/User-Experience/Research-Syntheses/2022%2C%20Winter%20-%20Understanding%20How%20STTs%20Would%20Use%20the%20Transmission%20Report%20copy.md

2024-03-12 20:26 UTC, reitermb commented
@lfrohlich All those fixes should be addressed now + one more formatting fix I found!

2024-03-15 16:39 UTC, lfrohlich approved these changes
Thanks for making these changes.

2024-03-18 17:56 UTC, merged