Sprint 95 summary
raft-tech/TANF-app pull request #2900
Opened 2024-03-26 15:44 UTC by robgendron

## Summary of Changes

This adds the Sprint 95 Summary

2024-03-26 16:50 UTC, andrew-jameson approved these changes

2024-03-26 20:26 UTC, reitermb requested changes
Left one comment on #2861 getting merged since we had our sync this morning. Once that's updated we should be good to tag in Alex for review!

2024-03-26 20:26 UTC, reitermb commented on docs/Sprint-Review/sprint-95-summary.md
> +* [#2681 TANF Section 1 Validation cleanup](https://github.com/raft-tech/TANF-app/issues/2681)
@robgendron 2861 got merged since our sync—we can go ahead and move it up to Completed/Merged

2024-04-22 18:15 UTC, reitermb approved these changes

2024-04-29 16:12 UTC, lfrohlich approved these changes
LGTM

2024-05-01 16:10 UTC, merged