wip - Feat/2965 db seed impl
raft-tech/TANF-app pull request #3134
Opened 2024-08-07 20:54 UTC by andrew-jameson

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #_

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-09-03 13:40 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
> +        for stt in STT.objects.all():  # filter(id__in=range(1,2)):
I think `all` might be excessive here, might take in an argument that utilizes the range in the comment to have a more limited subset of STTs.

2024-09-03 13:41 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
> +                elif field.name == 'update':
I really wish I could condense this, but the value-add of this script isn't to generate a bunch of files that fail at the first line and get auto-rejected. Having a good header is paramount but there are enough differences in the headers of various files that I can no longer just use the hardcoded one-liner I had previously.

2024-09-03 13:42 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
> +""" class FieldFaker(faker.providers.BaseProvider):..."""
Should probably delete this, but wanted to leave myself this breadcrumb.

2024-09-09 13:02 UTC, elipe17 commented on tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
> +            if long_section in ['Active Case Data', 'Closed Case Data', 'Aggregate Data', 'Stratum Data']:
Is SSP covered with this too?

2024-09-09 13:34 UTC, andrew-jameson commented on tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
> +            if long_section in ['Active Case Data', 'Closed Case Data', 'Aggregate Data', 'Stratum Data']:
No, it definitely wouldn't. I'll get that fixed up

2024-09-09 13:56 UTC, elipe17 requested changes
This PR led me to find a very small but impactful error in another area of our parser code that causes this db seed implementation to generate zero valid records when the fix for the error is added. It's a bit verbose to explain here so I will bring it up today on OH and we can document it that way.

2024-09-09 18:19 UTC, elipe17 commented
```
2024-09-09 18:12:27,335 ERROR case_consistency_validator.py::validate:L159 :  Uncaught exception during category four validation.
Traceback (most recent call last):
  File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 156, in validate
    num_errors = self.__validate()
  File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 176, in __validate
    num_errors += self.__validate_section2(num_errors)
  File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 192, in __validate_section2
    num_errors += self.__validate_t5_atd_and_ssi()
  File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 484, in __validate_t5_atd_and_ssi
    dob_date = datetime.strptime(dob, '%Y%m%d')
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 08
```

2024-09-23 19:49 UTC, andrew-jameson commented
> ```
> 2024-09-09 18:12:27,335 ERROR case_consistency_validator.py::validate:L159 :  Uncaught exception during category four validation.
> Traceback (most recent call last):
>   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 156, in validate
>     num_errors = self.__validate()
>   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 176, in __validate
>     num_errors += self.__validate_section2(num_errors)
>   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 192, in __validate_section2
>     num_errors += self.__validate_t5_atd_and_ssi()
>   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 484, in __validate_t5_atd_and_ssi
>     dob_date = datetime.strptime(dob, '%Y%m%d')
>   File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
>     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
>   File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
>     raise ValueError("unconverted data remains: %s" %
> ValueError: unconverted data remains: 08
> ```

@elipe17 Are you fine resolving this in follow on #3177

2024-09-25 17:26 UTC, raftmsohani approved these changes

2024-09-30 14:00 UTC, elipe17 commented
> > ```
> > 2024-09-09 18:12:27,335 ERROR case_consistency_validator.py::validate:L159 :  Uncaught exception during category four validation.
> > Traceback (most recent call last):
> >   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 156, in validate
> >     num_errors = self.__validate()
> >   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 176, in __validate
> >     num_errors += self.__validate_section2(num_errors)
> >   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 192, in __validate_section2
> >     num_errors += self.__validate_t5_atd_and_ssi()
> >   File "/tdpapp/tdpservice/parsers/case_consistency_validator.py", line 484, in __validate_t5_atd_and_ssi
> >     dob_date = datetime.strptime(dob, '%Y%m%d')
> >   File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
> >     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
> >   File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
> >     raise ValueError("unconverted data remains: %s" %
> > ValueError: unconverted data remains: 08
> > ```
> 
> @elipe17 Are you fine resolving this in follow on #3177 ?

@andrew-jameson Ya I think it makes sense to discuss/fix the cat4 bug in a separate ticket and leave the case consistent DB seed work as the ticket you linked.

2024-09-30 14:02 UTC, elipe17 approved these changes

2024-10-08 13:08 UTC, merged