2910 Synthesis
raft-tech/TANF-app pull request #3153
Opened 2024-08-21 00:05 UTC by reitermb

## Summary of Changes
Adds research synthesis markdown & updates readme accordingly

Both can be demoed in the branch https://github.com/raft-tech/TANF-app/tree/2910synthesis/docs/User-Experience/Research-Syntheses

Note that the readme link will not work until the branch is merged.

2024-08-21 00:05 UTC, reitermb commented
Corrected my merging problem & opened up a new branch!

cc @ADPennington

2024-08-21 17:51 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
> +<table><thead><tr><th width="199">Enhancement</th><th width="197">Description</th><th>DAC Page</th><th width="80">Ticket</th><th>Recommended Priority</th></tr></thead><tbody><tr><td>Filter data files
@reitermb please check the bracket around the row referencing #3092

2024-08-21 17:55 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
> +The Django Admin Console (DAC) is an internal tool tailored for our OFA System Admin and DIGIT Team users. It allows for access to the Postgres database & system logs, managing user permissions, and
i think its important to clarify here that the permissions for each group are different. I wouldn't want to misrepresent privileged access. digit team's access to DAC is limited/not privileged. and actually needs to be locked down further (follow-on ticket)

2024-08-21 17:58 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
> +<table><thead><tr><th width="199">Enhancement</th><th width="197">Description</th><th>DAC Page</th><th width="80">Ticket</th><th>Recommended Priority</th></tr></thead><tbody><tr><td>Filter data files
re: #3095, my impression is that the summaries are in json format.

2024-08-21 18:04 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
> +<table><thead><tr><th width="199">Enhancement</th><th width="197">Description</th><th>DAC Page</th><th width="80">Ticket</th><th>Recommended Priority</th></tr></thead><tbody><tr><td>Filter data files
re: #3097 -- confirmed with Yun that she does not need multiselect on STTs on data files page and also wants to combine year and quarter into one fiscal period filter (as shown in search indexes pages.

2024-08-21 18:07 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
> +<table><thead><tr><th width="199">Enhancement</th><th width="197">Description</th><th>DAC Page</th><th width="80">Ticket</th><th>Recommended Priority</th></tr></thead><tbody><tr><td>Filter data files
re: #3096 -- the explanation needs clarity. OFA groups want  to be able to see which case/months are associated with cat 1 and cat 4 errors. please see legacy system transmission emails for reference.

2024-08-21 18:10 UTC, ADPennington requested changes
@reitermb please see comments regarding changes requested.

2024-08-23 20:36 UTC, reitermb commented
> @reitermb please see comments regarding changes requested.

Everything should be updated now! Also fixed one last formatting issue that was making some of the tables look funky.

2024-08-27 13:07 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
> +We ran two workshops with the DIGIT team; which overlaps with our two OFA System Admins. While those teams overlap, note that the permissions for each user group differ. OFA System Admins have privel
```suggestion
We ran two workshops with the DIGIT team; which overlaps with our two OFA System Admins. While those teams overlap, note that the permissions for each user group differ. OFA System Admins have privileged access to DAC while DIGIT team users have non-privileged access. Our product manager and two developers were also in attendance for alignment and work estimation purposes. These workshops facilitated conversation around DAC enhancement requests & pain points provided by OFA in tickets [#2930](https://github.com/raft-tech/TANF-app/issues/2930), [#1662](https://github.com/raft-tech/TANF-app/issues/1662), [#960](https://github.com/raft-tech/TANF-app/issues/960), and [#2910](https://github.com/raft-tech/TANF-app/issues/2910) in order to achieve:
```

2024-08-27 13:12 UTC, ADPennington requested changes
- minor change requested
- recommendation to refine any attached tickets that do not currently include visuals of the behavior needing the enhancement. 

@victoriaatraft @reitermb @robgendron

2024-08-28 14:34 UTC, ADPennington approved these changes
Lgtm 👍🏾 cc: @ttran-hub @lfrohlich

2024-08-28 14:44 UTC, victoriaatraft commented
> * recommendation to refine any attached tickets that do not currently include visuals of the behavior needing the enhancement (not needed for PR approval, but for reference to those who review this synthesis in the future)

Also noted @ADPennington :)

2024-08-28 20:54 UTC, merged