Update personas document for issue #3100
raft-tech/TANF-app pull request #3214
Opened 2024-10-07 15:03 UTC by victoriaatraft

Updated OFA analysts description tables and added OFA Data Analyst Persona

## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #_

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-10-09 19:48 UTC, reitermb approved these changes
Final tweaks discussed in internal UX sync, good to QASP!

2024-10-11 13:54 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Goals<br /><br /><br />             | 1. Ensure availability of features and components of the system <br />2. Work with regional OFA staff to confirm who should and shouldn't be granted access to
```suggestion
| Goals<br /><br /><br />             | 1. Ensure availability of features and components of the system <br />2. Work with regional OFA staff to confirm who should and shouldn't be granted access to the system<br />3. Access system logs to troubleshoot problems and remediate scans as needed <br />4. Provide access to OCIO (ACF-Tech) staff for security auditing purposes <br />5. Monitoring emails, notifications and answering STT Questions |
```

2024-10-11 13:58 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Pain Points<br /><br /><br /><br /> | 1. "Django doesn't have all the filters I need to efficiently use it for certain admin tasks" <br /> 2. "The system can sometimes log me out with no warning" <
```suggestion
| Pain Points<br /><br /><br /><br /> | 1. "Django doesn't have all the filters I need to efficiently use it for certain admin tasks" <br /> 2. "The system can sometimes log me out with no warning" <br/> 3. Accessing data from cloud.gov-brokered databases is only possible by disconnecting from the HHS network on site and VPN when remote. <br/> 4. The toolstack needed as an administrator can be difficult to use on a Windows GFE <br/> 5. Requesting access to developer tools can take months at a time to get approved                           |
```

2024-10-11 13:59 UTC, ADPennington commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Expectations | 1. TDP should help sys admin do things from an interface as much as possible <br /> 2. We have to have another way to troubleshoot and remediate issues |
```suggestion
| Expectations | 1. TDP should help sys admin do things from an interface as much as possible <br /> 2. We need to have multiple ways to troubleshoot and remediate issues |
```

2024-10-11 14:00 UTC, ADPennington requested changes
in pretty good shape! a few edit suggestions

2024-10-11 16:09 UTC, ADPennington approved these changes
lgtm @victoriaatraft 👍🏾 tagging @ttran-hub here for review because i wasnt able add him as a reviewer on this PR for some reason.

2024-10-15 15:24 UTC, lfrohlich requested changes
Looking good! Made some minor comments

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> -OFA analysts review, analyze, and report on STT’s TANF data that’s submitted through TDP. They also help STTs through the transmission process by offering support and guidance around data quality (in
Please delete "(including fatal/warning edits)".

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
Please change grantee to STT under regional program specialist

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Age                                 | 37                                                           |
Can Elliott be 46 or something?

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Work Environment                    | Home and Office, Office                                      |
```suggestion
| Work Environment                    | Home and Office|
```

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Location                            | USA, Occassionally In Office DC                              |
```suggestion
| Location                            | USA, Occasionally In DC Office                              |
```

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +Research up to this point has suggested a need for three working personas; an OFA Data Analyst (Grace), an OFA System Admin (Elliott), and an STT data analyst. While these don't reflect the full dive
```suggestion
Research up to this point has suggested a need for three working personas: an OFA Data Analyst (Grace), an OFA System Admin (Elliott), and an STT data analyst. While these don't reflect the full diversity of  roles, responsibilities, and team makeups on both the grantee and federal levels, the "jobs to be done" for each in the context of TDP have a lot of overlap. A single persona could also have many different combinations of permissions available to them in the data portal. 
```

2024-10-15 15:24 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +To view a further in depth system of the interactions, primary tasks and touchpoints taken by OFA System Admins, please refer to the ecosystem map in the supporting documents below.
```suggestion
To view a further in-depth system of the interactions, primary tasks and touchpoints taken by OFA System Admins, please refer to the ecosystem map in the supporting documents below.
```

2024-10-15 17:52 UTC, victoriaatraft commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +| Age                                 | 37                                                           |
updated

2024-10-16 17:08 UTC, lfrohlich commented on docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
> +- [Ecosystem Map OFA System Admin](https://app.mural.co/t/raft2792/m/raft2792/1728311825176/74942929a28857c3ef1c401f0d07ccfe1073e882?sender=uf443e00cb4626b8bec157528)
Can you add the :lock: icon to the last link? 
```suggestion
- [Ecosystem Map OFA System Admin](https://app.mural.co/t/raft2792/m/raft2792/1728311825176/74942929a28857c3ef1c401f0d07ccfe1073e882?sender=uf443e00cb4626b8bec157528) :lock:
```

2024-10-16 17:09 UTC, lfrohlich requested changes
One minor thing, then will be all good to go!

2024-10-22 22:30 UTC, reitermb commented
> One minor thing, then will be all good to go!

Committed! Back over to QASP

2024-10-23 15:49 UTC, lfrohlich approved these changes
LGTM

2024-10-25 16:09 UTC, merged