1577 - Upgrade frontend deps
raft-tech/TANF-app pull request #3327
Opened 2024-12-03 18:40 UTC by jtimpe

## Summary of Changes
Pull request closes #1577 

The goal of this was primarily to get `react-scripts` updated to version 5. I took the opportunity to bump all the dependencies to the latest possible (downgrading a select few only to avoid conflicts). Along the way, the following tasks were also necessary
* Upgrading SASS and changing all imports to match the new module syntax
* Upgrading USWDS to version 3 (with support for the new SASS module syntax). Also required changing the import syntax for many components.
* A small set of changes to implement React 18
* Replace the `file-type` library (requires node runtime, no longer compatible) with `file-type-checker` (browser runtime)
* Configure jest to ignore the node/browser conflict for some packages (uswds and axios)
* Changing the linter configuration to ignore new es6 rules (trailing comma)

The following tickets were created as follow-on work
* Frontend dependency security vulnerabilities
* Frontend testing library deprecations
* Frontend defaultprops deprecation
* Frontend span warning
* Frontend a11y compliance (tbd if needed)
* Frontend router deprecations
* Frontend `fetch` to replace `axios`
* Update uswds again to resolve sass deprecations

## How to Test
```
cd tdrs-backend && docker compose up --build
cd tdrs-frontend && docker compose up --build
```

1. Open http://localhost:3000/ and sign in.
2. Navigate the frontend and test critical features (file upload, download, search form behaviors, navigation)
3. Test a11y compliance

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] react-scripts is updated to latest major version
+ [ ] file-type is ~~updated to latest major version~~ replaced with a browser-runtime-compatible alternative
+ [ ] package.json is updated
+ [ ] package-lock.json is updated
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-12-04 22:25 UTC, reitermb requested changes
I want to spend more time with this and test across a few different devices/OSes but for the most part this is already looking pretty good! 

Automated scans I've run so far are showing up clear and I've only turned up a handful of issues (mix of a11y and general QA) with initial manual testing:

https://app.mural.co/t/raft2792/m/raft2792/1733347565459/e9b8748c8dbe09f65e57d9c07d07b506daf102e0?sender=ufa4902beba666df5bec09412

I'll confirm for sure in a subsequent review but it looks like this has fixed #2307 as expected.

2024-12-10 14:31 UTC, jtimpe commented
thank you @reitermb! i've reviewed your suggestions and made three tickets. The `usa-hero` padding was an easy enough fix, so i went ahead and pushed that

![image](https://github.com/user-attachments/assets/574f4b0b-ab08-4885-bad9-451efdde4daa)

* Tab/screen-reader focus issues on Data Files page - #3352 
* GovBanner open by default - #3353 
* Disappearing files bug - #3354

2024-12-10 19:23 UTC, elipe17 approved these changes
I didn't find any other issues. Everything that I tried worked like a charm and didn't look weird! Great work on this!

2024-12-10 19:23 UTC, elipe17 commented on tdrs-frontend/src/components/FileUpload/FileUpload.jsx
> +      } else {
Love how much nicer this all is now!

2024-12-11 14:31 UTC, andrew-jameson approved these changes

2024-12-13 14:00 UTC, raftmsohani approved these changes
all good!

2024-12-13 14:00 UTC, raftmsohani commented on tdrs-frontend/src/assets/Button.scss
> +@use "uswds-core" as *;
Not related to this specific file but I am getting error on some of the CSS  and JS assets, my best guess is that new changes want these to be available in the frontend, but we are relaying all /static files to backend (maybe?!!):

<img width="907" alt="Screenshot 2024-12-04 at 11 27 33 AM" src="https://github.com/user-attachments/assets/cfac0440-9c52-46e7-b78d-804d58cbf91f">

2024-12-13 16:48 UTC, victoriaatraft approved these changes

2024-12-16 16:19 UTC, reitermb commented
> thank you @reitermb! i've reviewed your findings and made three tickets. The `usa-hero` padding was an easy enough fix, so i went ahead and pushed that
> 
> ![image](https://private-user-images.githubusercontent.com/111305129/394314849-574f4b0b-ab08-4885-bad9-451efdde4daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjU2NDEsIm5iZiI6MTczNDM2NTM0MSwicGF0aCI6Ii8xMTEzMDUxMjkvMzk0MzE0ODQ5LTU3NGY0YjBiLWFiMDgtNDg4NS1iYWQ5LTQ1MWVmZGRlNGRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNjA5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWNkMmUyZjA1ZmRmMmUyNGRkMzZlMjYyZDBhMzBlMDIzODg2ZmM1MDQ4ODJmOGJhZTM2NjI0NDNkNTA4YjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L7sZLyDN-w9KApJVbUY2AdH1gvlwvFlyjiRR1TRTGX8)
> 
> * Tab/screen-reader focus issues on Data Files page - [Reports.jsx search result header does not tab focus #3352](https://github.com/raft-tech/TANF-app/issues/3352)
> * GovBanner open by default - [GovBanner Component is open by default #3353](https://github.com/raft-tech/TANF-app/issues/3353)
> * Disappearing files bug - [Data Files page search results don't load the first time #3354](https://github.com/raft-tech/TANF-app/issues/3354)

Thanks @jtimpe! Just to make sure it's here too I'm good signing off of the padding fix. Just to track some of the more complicated followup a11y testing, in terms of next steps is the plan to merge this or keep it open until the spinoff fixes are added?

2024-12-16 16:19 UTC, reitermb approved these changes

2024-12-16 16:28 UTC, jtimpe commented
> Thanks @jtimpe! Just to make sure it's here too I'm good signing off of the padding fix. Just to track some of the more complicated followup a11y testing, in terms of next steps is the plan to merge this or keep it open until the spinoff fixes are added?

Thanks @reitermb! And that's a good question. Perhaps @andrew-jameson or @ADPennington could weigh in. My assumption was that we'd merge/close this and work the follow-on tickets based on priority.

2025-01-03 15:59 UTC, ADPennington approved these changes
> > Thanks @jtimpe! Just to make sure it's here too I'm good signing off of the padding fix. Just to track some of the more complicated followup a11y testing, in terms of next steps is the plan to merge this or keep it open until the spinoff fixes are added?
> 
> Thanks @reitermb! And that's a good question. Perhaps @andrew-jameson or @ADPennington could weigh in. My assumption was that we'd merge/close this and work the follow-on tickets based on priority.

I tested the userflows for acf and non-acf users for sign-in, request access, and data submission, and viewing error reports. LGTM 🚀  This can be merged. In terms of priority of the follow-on tickets:

1) #3328 (security fix)
2) #3353 (distracting user experience)
3) #3354  (pre-existing bug)
4) #3352 (pre-existing bug)

2025-01-03 18:55 UTC, merged