SSP M2 CITIZENSHIP_STATUS Cat3 Update
raft-tech/TANF-app pull request #3338
Opened 2024-12-04 18:53 UTC by elipe17

## Summary of Changes
- Updated the cat3 validator to accept 3 as a valid value for CITIZENSHIP_STATUS
- ~Waiting on feedback to determine whether we are changing "alien" references to "non-citizen"~
Pull request closes #3320 

## How to Test
```
cd tdrs-frontend && docker-compose up
cd tdrs-backend && docker-compose up
```

1. Open http://localhost:3000/ and sign in.
2. Submit a section 1 ssp file that has CITIZENSHIP_STATUS=3 and CITIZENSHIP_STATUS=9 verify no cat3 error generated when CITIZENSHIP_STATUS=3 and that a cat3 error is generated when CITIZENSHIP_STATUS=9

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] Cat 3 Validator logic for Items 26 and 38  is revised to allow 3  as an acceptable value for citizenship .
- [x] Error message related to Items 26 and 38 should be updated to reflect correct expected options.
- [x] Cat 3 Validator logic for Items 60 and 69 is revised to allow 3 as an acceptable value for citizenship .
- [x] Error message related to Items 60 and 69 should be updated to reflect correct expected options.
- [ ] ~references to "alien" in the codebase is changed to "non-citizen" (`on hold`)~ Alex writing new ticket for this.
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-12-04 18:54 UTC, andrew-jameson approved these changes

2024-12-04 19:27 UTC, jtimpe approved these changes

2024-12-05 11:24 UTC, raftmsohani approved these changes

2024-12-06 16:04 UTC, ADPennington requested changes
change requested re: [this comment](https://github.com/raft-tech/TANF-app/issues/3320#issuecomment-2521563697) . I missed the related validators in the M3 record.

2024-12-06 21:22 UTC, ADPennington approved these changes
🚀 appreciate the quick fix @elipe17 cc: @victoriaatraft @reitermb 

confirmed that the following error messages no longer present in SSP Active files:

`Since Item 26 (Family Affiliation) is 1, then Item 38 (Citizenship/Immigration Status) 3 must be one of (1, 2)`
`Since Item 60 (Family Affiliation) is 1, then Item 69 (Citizenship/Immigration Status) 3 must be one of (1, 2)`

2024-12-09 17:09 UTC, merged