Simplify File Ext Error Message
raft-tech/TANF-app pull request #3393
Opened 2024-12-31 17:11 UTC by elipe17

## Summary of Changes
- Updated the error message to contain the new message and a link to the KC.
Pull request closes #2873 

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose up --build
cd tdrs-backend && docker-compose up
```

1. Open http://localhost:3000/ and sign in.
2. Go to the datafiles page and try to upload a file with an incorrect extension
3. Verify error message is displayed and that the link to the KC works

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [ ] Error language is updated to "Invalid extension, please upload a .txt file. [Need help?](https://tdp-project-updates.app.cloud.gov/knowledge-center/file-extension-guide.html)" (link not env dependent, follow pattern for knowledge center links on homepage/footer)
    - [ ] update `INVALID_EXT_ERROR` in `FileUpload.jsx`
- [ ] Link points toward knowledge center guidance delivered in #2847 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

2024-12-31 17:13 UTC, andrew-jameson approved these changes

2024-12-31 17:14 UTC, elipe17 commented
@andrew-jameson and @reitermb since the error message indicates that a user should only submit a text file, should we also update the frontend validation to only accept the .txt extension? Currently it will allow files with: .txt, .ms00, .ts00, or .tx000.

2024-12-31 17:21 UTC, andrew-jameson commented
> @andrew-jameson and @reitermb since the error message indicates that a user should only submit a text file, should we also update the frontend validation to only accept the .txt extension? Currently it will allow files with: .txt, .ms00, .ts00, or .tx000.

I think you're right, that's what the error message provided in the ACs says and makes sense to enforce that.

2025-01-02 14:19 UTC, raftmsohani approved these changes
LGTM!

2025-01-02 16:02 UTC, victoriaatraft approved these changes
<img width="1491" alt="Screenshot 2025-01-02 at 7 59 19 AM" src="https://github.com/user-attachments/assets/935c2049-0570-4317-9505-21f304e6331d" />
LGTM from AxeDev Tool perspective, but the image in the KC that the link redirects too https://tdp-project-updates.app.cloud.gov/knowledge-center/file-extension-guide.html will need to be updated if not already.

2025-01-02 22:10 UTC, reitermb requested changes
One small tweak, could we change the aria-label to:

```aria-label="Need help? Read file extension guidance"```

There are some situations where the aria-label will override the link text being read, hence [starting the label with the link text itself](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8#:~:text=Per%20the%20Accessible,communication%20between%20users.).

Good to go with that!

2025-01-03 19:47 UTC, reitermb approved these changes

2025-01-03 20:00 UTC, ADPennington commented
@elipe17 merge conflict on this one

2025-01-03 20:17 UTC, elipe17 commented
> @elipe17 merge conflict on this one. also im curious if we are now requiring the legacy file naming conventions to change? I dont think we want to require that change.

I can definitely revert the change that forces .txt extensions only. I think in that case the error message would need some word smithing factor to that in

2025-01-08 15:22 UTC, elipe17 commented on tdrs-frontend/src/components/FileUpload/FileUpload.jsx
> +    Invalid extension, please upload a .txt file.&nbsp;
@reitermb, @victoriaatraft do we need iterate on this message? Alex wanted to still allow files with extensions like ".ms##" or ".ts###" to be uploaded. If a user does upload a file that causes an error they'll see that they should only upload a ".txt" when they do have a few other options. The KC still calls out the other options but this message doesnt

2025-01-09 22:31 UTC, reitermb commented on tdrs-frontend/src/components/FileUpload/FileUpload.jsx
> +    Invalid extension, please upload a .txt file.&nbsp;
Yes, I believe we landed on returning to the original error message + the Need Help? link addition with @ADPennington yesterday. 

e.g., 
![image](https://github.com/user-attachments/assets/d0100231-0f7d-477d-9c8b-434d616ba4c1)

2025-01-15 14:10 UTC, ADPennington commented
@elipe17 when you get a chance, can you re-deploy this PR to qasp env with the updated error message? cc: @ttran-hub

2025-01-15 19:41 UTC, ADPennington approved these changes
this looks great. thanks @elipe17 @victoriaatraft @reitermb cc: @ttran-hub @klinkoberstar 

I'm assuming the image in the TDP KC is being updated in #3425, right? 

_before_

![file_ext_before](https://github.com/user-attachments/assets/ddf11130-66a2-4116-a0b5-374259fc9ddc)


_after_
![file_ext_after](https://github.com/user-attachments/assets/af18aaa8-7304-40bc-8dd0-d8c82f43fb65)

2025-01-15 20:01 UTC, victoriaatraft commented
Yup! @ADPennington it's part of the upcoming release notes :)

2025-01-15 20:04 UTC, merged