Epic/9/issue/352/groupless user list
raft-tech/TANF-app pull request #432
Opened 2020-11-20 20:07 UTC by riatzukiza

### This pull request changes...

Adds an endpoint to list all users with out a group

## FUNCTIONALITY
*Describe the functionality*
*Addresses Issue #352*

## TO TEST

*List the steps to test the PR*

### This pull request is ready to merge when...

- [ ] Meets acceptance criteria for the issue 
- [ ] Code is reviewed by someone other than the original author
- [ ] Code is tested 
- [ ] Experience is approved by UX  
- [ ] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [ ] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [ ] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

2020-11-27 20:09 UTC, carltonsmith requested changes
@riatzukiza This looks great, but there are some linting problems. If you can update those we can continue to Raft Review

2020-12-10 20:11 UTC, carltonsmith requested changes
Great work! There are a couple of adjustments, but not much.

2020-12-10 20:11 UTC, carltonsmith commented on tdrs-backend/docs/api/groupless_users.md
> +]
I think this list should include the STT as the OFA Analysts and Admins will need to know that to help identify the user for approval and role assignment

2020-12-10 20:11 UTC, carltonsmith commented on tdrs-backend/docs/api/groupless_users.md
> +
This list should only be accessible to the OFA Admin and Superuser roles (and maybe OFA Analyst, I will confirm). We should have that in the documentation.

2020-12-10 20:11 UTC, carltonsmith commented on tdrs-backend/docs/api/groupless_users.md
> +Group matching query does not exist.
Shouldn't this return a `403 FORBIDDEN` response?

2020-12-10 20:11 UTC, carltonsmith commented on tdrs-backend/tdpservice/users/test/test_api.py
> +
I think a test confirming that a user with a group does not appear in the list would be helpful

2021-02-18 22:48 UTC, jtwillis92 commented
@riatzukiza @carltonsmith is this PR still in progress or has this work been postponed?

2021-02-19 14:40 UTC, carltonsmith commented
> @riatzukiza @carltonsmith is this PR still in progress or has this work been postponed?

Yes, this changed when we decided to go with Django Admin. I'll close it now.

2021-02-19 14:40 UTC, closed without merging