Update our-workflow.md
raft-tech/TANF-app pull request #740
Opened 2021-03-05 17:59 UTC by kniz-raft

### Summary of Changes
_Updates documentation as a result of ADR 009 and new team members being added_
_Addresses issue #700_

2021-03-05 18:11 UTC, carltonsmith requested changes
One small change, but looks great!

2021-03-05 18:11 UTC, carltonsmith commented on docs/How-We-Work/team-charter/our-workflow.md
> +- Ad hoc pairing or scheduled pairing session(s) with 18F are encouraged throughout the sprint to increase transparency and familiarity with the issue
I would say
> ... with 18F and ACF Tech Lead...

2021-03-05 18:18 UTC, kniz-raft commented on docs/How-We-Work/team-charter/our-workflow.md
> +- Ad hoc pairing or scheduled pairing session(s) with 18F are encouraged throughout the sprint to increase transparency and familiarity with the issue
Good catch - updated. Thanks!

2021-03-05 18:41 UTC, carltonsmith approved these changes
LGTM!

2021-03-08 16:29 UTC, ADPennington reviewed
lgtm. general question: do we need to call out the security control-related workflow? It is reflected in the ADR#9 which is referenced here, so maybe that's sufficient?

2021-03-08 16:33 UTC, lfrohlich commented
> lgtm. general question: do we need to call out the security control-related workflow? It is reflected in the ADR#9 which is referenced here, so maybe that's sufficient?

That's a good point. Maybe we could say something like "see ADR#9 including security control-related workflow"

2021-03-08 16:34 UTC, lfrohlich commented
Looks good -- one suggestions that "The product owner proposes the issues for the next sprint" could be expanded to say issues come from PM/leads/Tech Lead, and PO.

2021-03-08 18:11 UTC, lfrohlich approved these changes
THanks for making that change!

2021-03-08 18:36 UTC, kniz-raft commented
> THanks for making that change!

Sure thing - @ADPennington I added more context around ADR #009 too if you want to take a look.

2021-03-08 18:38 UTC, merged

2021-03-08 18:38 UTC, ADPennington approved these changes
Looks good! Thanks @kniz-raft