[WIP] Issue 374: Use UUID instead of email address during login.gov setup
raft-tech/TANF-app pull request #894
Opened 2021-05-05 23:20 UTC by jorgegonzalez

### Summary of Changes
_Provide a brief summary of changes_
_Addresses issue #374 
_Acceptance criteria as stated in the issue_

### How to Test
_List the steps to test the PR_

### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

+ [ ] Look up the acceptance criteria in the related issue; paste ACs below in checklist format.
+ [ ] Check against the criteria:

As facilitator/product manager, @kniz-raft will decide if ACs are met from Raft's perspective.

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Backend coverage: ___ (see https://github.com/raft-tech/TANF-app README coverage dashboard)

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

+ [ ] Are backend code style checks passing on CircleCI?

### Deliverable 4: Accessible

### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful build with a single command*

> NOTE: until we have a proper staging environment this may not be satisfiable prior to merging

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

+ [ ] If this PR introduces backend code, is that code documented both inline and overall?
+ [ ] If this PR introduces frontend code, is that code documented both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any security issues?

2021-05-11 01:06 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/api/login.py
> +                        "Email verified, but experienced internal issue "
Fixing a typo

2021-05-11 01:07 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/test/test_auth.py
> +            "Email verified, but experienced internal issue " "with login/registration."
Fixing corresponding typo above.

2021-05-11 01:08 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/test/test_auth.py
> +    inactive_user.username = "test_inactive@example.com"
These and others below were renamed to fix an IntegrityError; the `sub` values were updated to account for new auth method.

2021-05-11 01:08 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/migrations/0013_user_sub.py
> +# Generated by Django 3.1.7 on 2021-05-10 14:10
This migration is autogenerated from the addition of the `UUIDField` to the `User` model.

2021-05-11 01:09 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/models.py
> +    sub = models.UUIDField(editable=False, blank=True, null=True, unique=True)
As noted above, this will addition will generate a corresponding migration file to apply to the DB.

2021-05-11 01:11 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/api/login.py
> +        if (su_username := os.environ.get('DJANGO_SU_NAME')) and su_username == email:
There is an edge case where we need to save the unique `sub` value of the initial superuser defined by `DJANGO_SU_NAME`. In this branch, we must therefore authenticate with the email. All other authentications will later be done using this `sub` value: `user_id=sub`.

2021-05-11 01:12 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/api/login.py
> +            if user.username != email:
If the user update's their email externally, we manually update it here so it can be used in future login attempts.

2021-05-11 01:12 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/api/login.py
> +            user = User.objects.create_user(email, email=email, sub=sub)
Create new `Users` with the `email` set to `username` by default.

2021-05-11 01:13 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/authentication.py
> +            except User.DoesNotExist:
Bypass the default authentication branch, and find a user by their unique `sub` `user_id` value.

2021-05-11 01:15 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/test/test_auth.py
> +def test_login_with_old_email(mocker, api_client, user):
This tests that user's who try to login with an old email then have their email updated with the one in the `decoded_token` from the auth payload.

2021-05-11 01:15 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/test/test_auth.py
> +def test_login_with_initial_superuser(mocker, api_client, user):
This tests that the initial superuser gets the proper `sub` value after their initial login attempt.

2021-05-18 20:35 UTC, jtwillis92 requested changes
Looks good, 1 small nit for a more explicit name and then I'd also request adding this new field to the UserAdmin so we can view the value in Django Admin as part of the testing steps.

2021-05-18 20:35 UTC, jtwillis92 commented on tdrs-backend/tdpservice/users/models.py
> +    sub = models.UUIDField(editable=False, blank=True, null=True, unique=True)
```suggestion
    login_gov_uuid = models.UUIDField(editable=False, blank=True, null=True, unique=True)
```

2021-05-19 19:27 UTC, jorgegonzalez commented on tdrs-backend/tdpservice/users/models.py
> +    sub = models.UUIDField(editable=False, blank=True, null=True, unique=True)
Done, thanks!

2021-05-20 22:03 UTC, jorgegonzalez commented
Ah I still need to add this to the UserAdmin.

2021-05-26 21:39 UTC, jtwillis92 approved these changes
Tested locally and confirmed that the UUID from Login.gov is correctly associated with my user account and visible from within the Django Admin User details page.

2021-05-28 16:30 UTC, ADPennington commented
test results below.  👍🏾 

- signed in successfully as a superuser >> confirmed the addition of the uuid from the user profile page in django admin
- signed in as a new user >> confirmed the presence of the uuid for this user in django admin using superuser account
- changed an existing user's email address via login.gov >> signed back into tdp as an existing user with new email address >> confirmed that this new email address replaces old one in django admin (also uuid stayed the same as expected)
- as a superuser, changed another user's email address via django admin >> confirmed that this change was overwritten when the user signed in using their login.gov credentials. no changes to uuid, as expected.

2021-06-02 19:14 UTC, merged